services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./docs:/app/docs
      - ./scripts:/app/scripts
    environment:
      - ENVIRONMENT=development
      - QDRANT_URL=http://qdrant:6333
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - hvac_net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - hvac_net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    networks:
      - hvac_net

  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_storage:/qdrant/storage
  #   environment:
  #     - QDRANT__SERVICE__HTTP_PORT=6333
  #   networks:
  #     - hvac_net

volumes:
  qdrant_storage:

networks:
  hvac_net: